# Generated by Django 4.2 on 2023-05-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=250, verbose_name='endereço')),
            ],
        ),
    ]
